version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: scripts/stop-container.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/start-new-container.sh
      timeout: 300
      runas: ec2-user