version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - apt-get update
      - apt-get install  openjdk8
      - apt-get install  maven
      - apt-get update
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker version
      - docker login --username=$DOCKER_USER --password=$DOCKER_PASS
  build:
    commands:
      - echo Build started on `date`
      - echo run tests
      - mvn test
      - echo packaging
      - mvn package
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing docker image to docker hub
      - docker push $REPOSITORY_URI:$IMAGE_TAG