version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  prebuild:
    commands:
      - echo Logging in to Docker Hub...
      - docker version
      - docker login --username=$DOCKER_USER --password=$DOCKER_PASS --email=$DOCKER_EMAIL
  build:
    commands:
      - echo Build started on `date`
      - echo run tests
      - mvn test
      - echo packaging
      - mvn package
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing docker image to docker hub
      - docker push $REPOSITORY_URI:$IMAGE_TAG